/*
LeetCode: 389. Find the Difference
Learning: Hash Table, String, Bit Manipulation, Sorting
Description: You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 
*/

#include <bits/stdc++.h>
using namespace std;

char findTheDifference(string s, string t) {
    sort(s.begin(), s.end());
    sort(t.begin(), t.end());
    s.append("0");
    for (int i = 0; i < t.size(); i++) {
        if (s[i] != t[i]) return t[i];
    }
    return 'a';
}

int main() {

    string s = "abcd", t = "abcde";
    cout << findTheDifference(s, t) << endl;

  return 0;
}